steps:
  - label: ":hammer: Example Script"
    plugins:
      - https://github.com/fatteneder/diff-filter-buildkite-plugin.git#main:
          name: "docs"
          match:
            - "testdir/docs/*"
      - https://github.com/fatteneder/diff-filter-buildkite-plugin.git#main:
          name: build
          match:
            - "testdir/*"
          ignore:
            - "testdir/**/*.md"
    commands: |
      if [[ $${BUILDKITE_PLUGIN_DIFF_FILTER_TRIGGERED_DOCS} == 1 ]]; then
        script.sh
      fi
      if [[ $${BUILDKITE_PLUGIN_DIFF_FILTER_TRIGGERED_BUILD} == 1 ]]; then
        script.sh
      fi
    artifact_paths: "artifacts/*"
