steps:
  - label: ":hammer: Example Script"
    plugins:
      - library-example#v1.0.0: ~
      - https://github.com/fatteneder/diff-filter-buildkite-plugin#9cd148a13b87aa0d32c28e58d2d861c8bd047b66:
          name: "docs"
          match:
            - "testdir/docs/*"
      - https://github.com/fatteneder/diff-filter-buildkite-plugin#9cd148a13b87aa0d32c28e58d2d861c8bd047b66:
          name: "build"
          match:
            - "testdir/*"
          ignore:
            - "testdir/**/*.md"
    commands: |
      if [[ $${BUILDKITE_PLUGIN_DIFF_FILTER_TRIGGERED_DOCS} == 1 ]]; then
        script.sh
      fi
      if [[ $${BUILDKITE_PLUGIN_DIFF_FILTER_TRIGGERED_BUILD} == 1 ]]; then
        script.sh
      fi
    artifact_paths: "artifacts/*"
