steps:
  - label: ":hammer: Example Script"
    plugins:
      - library-example#v1.0.0: ~
      - https://github.com/fatteneder/diff-filter-buildkite-plugin.git#2bb2cf3d6f1644916155c4c9e3bb5b087815ebd9:
          name: "docs"
          match:
            - "testdir/docs/*"
      - https://github.com/fatteneder/diff-filter-buildkite-plugin.git#2bb2cf3d6f1644916155c4c9e3bb5b087815ebd9:
          name: "build"
          match:
            - "testdir/*"
          ignore:
            - "testdir/**/*.md"
    commands: |
      echo "Hello"
      echo $${BUILDKITE_PLUGIN_DIFF_FILTER_TRIGGERED_DOCS}
      echo $${BUILDKITE_PLUGIN_DIFF_FILTER_TRIGGERED_BUILD}
      echo "World!!!!"
      if [[ $${BUILDKITE_PLUGIN_DIFF_FILTER_TRIGGERED_DOCS} == 1 ]]; then
        script.sh
      fi
      if [[ $${BUILDKITE_PLUGIN_DIFF_FILTER_TRIGGERED_BUILD} == 1 ]]; then
        script.sh
      fi
    artifact_paths: "artifacts/*"
