steps:
  - label: ":hammer: Example Script"
    plugins:
      - library-example#v1.0.0: ~
      - https://github.com/fatteneder/diff-filter-buildkite-plugin#d4fec510a8fb036d1b91f93c1e6a494117e0be3d:
          name: "docs"
          match:
            - "testdir/docs/*"
      - https://github.com/fatteneder/diff-filter-buildkite-plugin#d4fec510a8fb036d1b91f93c1e6a494117e0be3d:
          name: "build"
          match:
            - "testdir/*"
          ignore:
            - "testdir/**/*.md"
    commands: |
      if [[ $${BUILDKITE_PLUGIN_DIFF_FILTER_TRIGGERED_DOCS} == 1 ]]; then
        script.sh
      fi
      if [[ $${BUILDKITE_PLUGIN_DIFF_FILTER_TRIGGERED_BUILD} == 1 ]]; then
        script.sh
      fi
    artifact_paths: "artifacts/*"
